<?php
/**
 * @file
 * Code for the GDPR feature.
 */

include_once 'gdpr.features.inc';

/**
 * Implements hook_entity_view_alter().
 */
function gdpr_entity_view_alter(&$build, $type) {
  if ($type != 'node')
    return;
  if ($build['#bundle'] != 'gdpr_processing')
    return;
  foreach (array('field_gdpr_controller_person') as $user_field) {
    if (isset($build[$user_field])) {
      $i = 0;
      while (isset($build[$user_field][$i])) {
        $u = $build[$user_field]['#items'][$i]['entity'];
        $build[$user_field][$i]['#markup'] = l($u->field_full_name['und'][0]['value'], 'http://www.uib.no/user/uib/' . $u->name);
        $i++;
      }
    }
  }
}

/**
 * Implements hook_form_alter().
 */
 function gdpr_form_gdpr_processing_node_form_alter(&$form, &$form_state, $form_id) {
  $form['field_gdpr_data_special_type']['#states'] = array(
    'visible' => array(
      ':input[name="field_gdpr_data_special[und]"]' => array('value' => 'y'),
    ),
  );
  $form['field_gdpr_data_special_lawfulne']['#states'] = array(
    'visible' => array(
      ':input[name="field_gdpr_data_special[und]"]' => array('value' => 'y'),
    ),
  );
}
