<?php
/**
 * @file
 * Code for the uib_setup feature.
 */

include_once 'uib_setup.features.inc';

/**
 * Implements hook_username_alter().
 *
 * The UiB user names are too ugly to show to regular people, so we want
 * users to be presented by their full name.
 */
function uib_setup_username_alter(&$name, $account) {
  if (isset($account->uid)) {
    $user = user_load($account->uid);
    if (!empty($user->field_full_name)) {
      $name = $user->field_full_name['und'][0]['safe_value'];
    }
  }
}
