<?php
/**
 * @file
 * Code for the Tjenestekatalog feature.
 */

include_once 'tk.features.inc';

/**
 * Implements hook_block_info().
 */
function tk_block_info() {
  return array(
    'traffic_light' => array(
      'info' => t('Service status'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function tk_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'traffic_light':
      $block['subject'] = "Driftstatus";

      $bad = array();

      $query = new EntityFieldQuery;
      $result = $query
        ->entityCondition('entity_type', 'node')
        ->propertyCondition('type', 'service')
        ->fieldCondition('field_service_status', 'value', 'normal', '!=')
        ->execute();
      if (!empty($result['node'])) {
        $nodes = node_load_multiple(array_keys($result['node']));
        foreach ($nodes as $node) {
          $bad[$node->field_service_status['und'][0]['value']][] = $node;
        }
      }

      if ($bad) {
        $content = array();
        foreach ($bad as $status => $services) {
          $content[$status] = array(
            '#theme' => 'item_list',
            '#title' => $status,
          );
          foreach ($services as $service) {
            $content[$status]['#items'][] = $service->title;
          }
        }
        $block['content'] = $content;
      }
      else {
        $block['content'] = '<div>' . t("Alle tjenester i normal drift") . '</div>';
      }

      break;
  }
  return $block;
}

function tk_entity_view_alter(&$build, $type) {
  if ($type != 'node')
    return;
  if ($build['#bundle'] != 'service')
    return;
  if (isset($build['field_cmdb_id'])) {
    $cmdb_id = $build['field_cmdb_id']['#items'][0]['value'];
    $build['field_cmdb_id'][0]['#markup'] = "<a href='https://bs.uib.no/?module=cmdb&action=viewt&tjeneste=$cmdb_id'>$cmdb_id</a>";
  }
  if (isset($build['field_operator'])) {
    $i = 0;
    while (isset($build['field_operator'][$i])) {
      $u = $build['field_operator']['#items'][$i]['entity'];
      $build['field_operator'][$i]['#markup'] = l($u->field_full_name['und'][0]['value'], 'http://www.uib.no/user/uib/' . $u->name);
      $i++;
    }
  }
}
