<?php
/**
 * @file
 * Code for the Tjenestekatalog feature.
 */

include_once 'tk.features.inc';

/**
 * Implements hook_menu().
 */
function tk_menu() {
  $items['api'] = array(
    'page callback' => 'tk__api_page',
    'access callback' => TRUE,
  );
  $items['api/v1/tk.json'] = array(
    'page callback' => 'tk__api_dump_json',
    'access callback' => TRUE,
  );
  $items['api/v1/service'] = array(
    'page callback' => 'tk__api_services',
    'access callback' => TRUE,
  );
  $items['api/v1/service/%'] = array(
    'page callback' => 'tk__api_service',
    'access callback' => TRUE,
    'page arguments' => array(3),
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function tk_block_info() {
  return array(
    'traffic_light' => array(
      'info' => t('Service status'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function tk_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'traffic_light':
      $block['subject'] = "Driftstatus";

      $bad = array();

      $query = new EntityFieldQuery;
      $result = $query
        ->entityCondition('entity_type', 'node')
        ->propertyCondition('type', 'service')
        ->fieldCondition('field_service_status', 'value', 'normal', '!=')
        ->execute();
      if (!empty($result['node'])) {
        $nodes = node_load_multiple(array_keys($result['node']));
        foreach ($nodes as $node) {
          $bad[$node->field_service_status['und'][0]['value']][] = $node;
        }
      }

      if ($bad) {
        $content = array();
        foreach ($bad as $status => $services) {
          $content[$status] = array(
            '#theme' => 'item_list',
            '#title' => $status,
          );
          foreach ($services as $service) {
            $content[$status]['#items'][] = $service->title;
          }
        }
        $block['content'] = $content;
      }
      else {
        $block['content'] = '<div>' . t("Alle tjenester i normal drift") . '</div>';
      }

      break;
  }
  return $block;
}

/**
 * Page callback
 */
function tk__api_page() {
  global $base_url;
  return <<<EOT
<style>
  article {
    margin: 2ex;
  }
  dl {
    margin: 0;
    padding-left: 2ex;
  }
</style>
<article>
  <h2>Tk API</h2>
  <p>Tk is our database of all IT services provided at the University of Bergen.  The data is exposed in
  machine readable formats for all to read.  APIs for updating our data is not yet available.

  <p>The official endpoints are:</p>
  <dl>
    <dt> <a href="/api/v1/tk.json">$base_url/api/v1/tk.json</a>
    <dd>This returns a complete dump all the services and related information such as users and categories.
  </dl>

  <p>Deprecated endpoints:</p>
  <dl>
    <dt> <a href="/data/tk.csv">$base_url/data/tk.csv</a>
    <dt> <a href="/data/tk.xls">$base_url/data/tk.xls</a>
  </dl>
</article>
EOT;
}



function tk__service_nids() {
  $query = new EntityFieldQuery;
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'service')
    //->propertyCondition('status', '1')
    ->execute();
  return empty($result['node']) ? array() : array_keys($result['node']);
}

/**
 * Page callback
 */
function tk__api_services() {
  $services = array();
  foreach (tk__service_nids() as $nid) {
    $services[] = array(
      'id' => $nid,
      'page' => url('node/' . $nid, array('absolute' => TRUE)),
      'info' => url('api/v1/service/' . $nid, array('absolute' => TRUE)),
    );
  }

  drupal_add_http_header('Access-Control-Allow-Origin', '*');

  return drupal_json_output(array(
    'version' => '0.9',
    'services' => $services,
  ));
}

function tk__service_node_as_obj($node) {
  $obj = array(
    'id' => $node->nid,
    'title' => $node->title,
  );
  return $obj;
}


/**
 * Page callback
 */
function tk__api_service($nid) {
  $node = node_load($nid);
  $obj = tk__service_node_as_obj($node);

  drupal_add_http_header('Access-Control-Allow-Origin', '*');

  $obj['version'] = '0.9';
  return drupal_json_output($obj);
}

/**
 * Page callback
 */
function tk__dump_json() {
  $services = array();
  $users = array();

  $query = new EntityFieldQuery;
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'service')
    //->propertyCondition('status', '1')
    ->execute();
  if (!empty($result['node'])) {
    $nodes = node_load_multiple(array_keys($result['node']));
    foreach ($nodes as $node) {
      $service = array(
        'title' => $node->title,
        //'nid' => $node->nid,
        'link' => array(
          'tk' => url('node/' . $node->nid, array('absolute' => TRUE)),
        ),
        'meta' => array(
          'created' => format_date($node->created, 'custom', 'Y-m-d H:i:s'),
          'changed' => format_date($node->changed, 'custom', 'Y-m-d H:i:s'),
        ),
      );

      //classification
      if ($node->field_service_classification) {
        foreach ($node->field_service_classification['und'] as $v) {
          $tid = $v['target_id'];
          $term = taxonomy_term_load($tid);
          $service['class'][] = $tid . " " . $term->name;
        }
      }

      // other links
      if ($node->field_home_link['und'][0]) {
        $service['link']['home'] = tk__url($node->field_home_link['und'][0]['url']);
        if ($node->field_home_link['und'][0]['title']) {
          $service['link']['_title_home'] = $node->field_home_link['und'][0]['title'];
        }
      }
      if ($node->field_documentation_link['und'][0]) {
        $service['link']['doc'] = tk__url($node->field_documentation_link['und'][0]['url']);
        if ($node->field_documentation_link['und'][0]['title']) {
          $service['link']['_title_doc'] = $node->field_documentation_link['und'][0]['title'];
        }
      }

      // include the user roles
      $author = user_load($node->uid);
      $service['role']['author'] = $author->name;
      $users[$author->name] = $account->field_full_name['und'][0]['value'];
      foreach (array('ower_contact', 'operator') as $role) {
        $field = "field_$role";
        $field = $node->$field;
        $role_users = array();
        foreach ($field['und'] as $u) {
          $account = user_load($u['target_id']);
          if ($account) {
            $role_users[$account->name] = TRUE;
            $users[$account->name] = $account->field_full_name['und'][0]['value'];
          }
          else {
            $role_users["unknown_" . $u['target_id']] = TRUE;
          }
        }
        if ($role_users) {
          $fixed_role = $role == 'ower_contact' ? 'owner' : $role;
          ksort($role_users);
          $service['role'][$fixed_role] = implode(' ', array_keys($role_users));
        }
      }

      // text fields
      foreach (array(
        'field_summary',
        'field_description',
        'field_demand',
        //'field_quality',
        'field_field_howto_orde',
        'field_supporting_systems',
        'field_internal_notes',
      )
      as $field) {
        $fv = $node->$field;
        if (isset($fv['und'][0])) {
          $text = $fv['und'][0]['value'];
          $text = str_replace("\r\n", "\n", $text);
          $service['text'][substr($field, 6)] = $text;
        }
      }

      $flag = array();
      if ($node->promote) {
        $flag[] = 'promote';
      }
      if ($node->status == 0) {
        $flag[] = 'unpublished';
      }
      if (!empty($flag)) {
        $service['flag'] = implode(' ', $flag);
      }

      //unset($service['text']);  // more compact output
      unset($users['admin']);

      $services[(string)$node->nid] = $service;
    }
  }

  ksort($users);

  drupal_add_http_header('Access-Control-Allow-Origin', '*');

  return drupal_json_output(array(
    'version' => '0.9',
    'service' => $services,
    'user' => $users,
  ));
}

function tk__url($url) {
  if (!strstr($url, ':')) {
    $url = "http://$url";
  }
  return $url;
}

/**
 * Implements hook_preprocess_HOOK().
 */
function tk_preprocess_links(&$vars) {
  if (isset($vars['links']['node-readmore'])) {
    unset($vars['links']['node-readmore']);
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function tk_entity_view_alter(&$build, $type) {
  if ($type != 'node')
    return;
  if ($build['#bundle'] != 'service')
    return;
  if (isset($build['field_cmdb_id'])) {
    $cmdb_id = $build['field_cmdb_id']['#items'][0]['value'];
    $build['field_cmdb_id'][0]['#markup'] = "<a href='https://bs.uib.no/?module=cmdb&action=viewt&tjeneste=$cmdb_id'>$cmdb_id</a>";
  }
  foreach (array('field_operator', 'field_ower_contact') as $user_field) {
    if (isset($build[$user_field])) {
      $i = 0;
      while (isset($build[$user_field][$i])) {
        $u = $build[$user_field]['#items'][$i]['entity'];
        $build[$user_field][$i]['#markup'] = l($u->field_full_name['und'][0]['value'], 'http://www.uib.no/user/uib/' . $u->name);
        $i++;
      }
    }
  }
}
