<?php
/**
 * @file
 * Code for the Tjenestekatalog feature.
 */

include_once 'tk.features.inc';

/**
 * Implements hook_menu().
 */
function tk_menu() {
  $items['data/services/v1'] = array(
    'page callback' => 'tk__services_list',
    'access callback' => TRUE,
  );
  return $items;
}

/**
 * Implements hook_block_info().
 */
function tk_block_info() {
  return array(
    'traffic_light' => array(
      'info' => t('Service status'),
    ),
  );
}

/**
 * Implements hook_block_view().
 */
function tk_block_view($delta = '') {
  $block = array();
  switch ($delta) {
    case 'traffic_light':
      $block['subject'] = "Driftstatus";

      $bad = array();

      $query = new EntityFieldQuery;
      $result = $query
        ->entityCondition('entity_type', 'node')
        ->propertyCondition('type', 'service')
        ->fieldCondition('field_service_status', 'value', 'normal', '!=')
        ->execute();
      if (!empty($result['node'])) {
        $nodes = node_load_multiple(array_keys($result['node']));
        foreach ($nodes as $node) {
          $bad[$node->field_service_status['und'][0]['value']][] = $node;
        }
      }

      if ($bad) {
        $content = array();
        foreach ($bad as $status => $services) {
          $content[$status] = array(
            '#theme' => 'item_list',
            '#title' => $status,
          );
          foreach ($services as $service) {
            $content[$status]['#items'][] = $service->title;
          }
        }
        $block['content'] = $content;
      }
      else {
        $block['content'] = '<div>' . t("Alle tjenester i normal drift") . '</div>';
      }

      break;
  }
  return $block;
}

/**
 * Page callback for data/services/v1
 */
function tk__services_list() {
  $data = array();

  $query = new EntityFieldQuery;
  $result = $query
    ->entityCondition('entity_type', 'node')
    ->propertyCondition('type', 'service')
    //->propertyCondition('status', '1')
    ->execute();
  if (!empty($result['node'])) {
    $nodes = node_load_multiple(array_keys($result['node']));
    foreach ($nodes as $node) {
      $service = array(
        'title' => $node->title,
        //'nid' => $node->nid,
        'created' => $node->created, // XXX iso time
        'changed' => $node->changed,
        'text' => array(
          'summary' => $node->field_summary['und'][0]['value'],
          'description' => $node->field_description['und'][0]['value'],
        ),
      );

      if (isset($node->field_internal_notes['und'][0])) {
        $service['text']['notes'] = $node->field_internal_notes['und'][0]['value'];
      }

      $flag = array();
      if ($node->promote) {
        $flag[] = 'promote';
      }
      if ($node->status == 0) {
        $flag[] = 'unpublished';
      }
      if (!empty($flag)) {
        $service['flag'] = $flag;
      }

      $data[(string)$node->nid] = $service;
    }
  }

  return drupal_json_output($data);
}

/**
 * Implements hook_preprocess_HOOK().
 */
function tk_preprocess_links(&$vars) {
  if (isset($vars['links']['node-readmore'])) {
    unset($vars['links']['node-readmore']);
  }
}

/**
 * Implements hook_entity_view_alter().
 */
function tk_entity_view_alter(&$build, $type) {
  if ($type != 'node')
    return;
  if ($build['#bundle'] != 'service')
    return;
  if (isset($build['field_cmdb_id'])) {
    $cmdb_id = $build['field_cmdb_id']['#items'][0]['value'];
    $build['field_cmdb_id'][0]['#markup'] = "<a href='https://bs.uib.no/?module=cmdb&action=viewt&tjeneste=$cmdb_id'>$cmdb_id</a>";
  }
  foreach (array('field_operator', 'field_ower_contact') as $user_field) {
    if (isset($build[$user_field])) {
      $i = 0;
      while (isset($build[$user_field][$i])) {
        $u = $build[$user_field]['#items'][$i]['entity'];
        $build[$user_field][$i]['#markup'] = l($u->field_full_name['und'][0]['value'], 'http://www.uib.no/user/uib/' . $u->name);
        $i++;
      }
    }
  }
}
