#!/bin/bash
datetime=$(date -I)T$(date +%H%M%S)
echo "Reset origin/staging to prod!!! (y/n)?"
read x
if ! [ $x == "y" ];then 
  echo User abort...
  exit
fi
#Check user
if ! [ $(whoami) == "app" ];then 
  echo wrong user Run as app >/dev/stderr
  exit 1
fi

#Check hostname
if ! [ $(hostname|egrep '^(long|real|double)6'|grep -v test|wc -l) -gt 0 ];then 
  echo wrong host >/dev/stderr
  exit 1
fi
set -x 
cd /var/www/app/tk/ || exit 1
#mkdir -p /nettapp_w3/pg_dump/pre_staging || exit 1
#DB-Dump
#bin/site-drush sql-dump --structure-tables-key=common > /nettapp_w3/pg_dump/pre_staging/w3.uib.no-staging-backup.${datetime}.sql || exit 1

git fetch --all --prune || exit 1
git reset --hard origin/master || exit 2
git status || exit 3
git submodule update || exit 4


set -x
echo "Confirm before feature revert is applied!!! (y/n)?"
read x
if ! [ $x == "y" ];then 
  echo User abort...
  echo TOTO: Reset using GIT...
  exit
fi
set x

cd /var/www/app/tk/drupal
#drush vset maintenance_mode 1

#compass compile --force -q themes/uib_zen
#find site/files/{css,js,languages} -type f -print | xargs rm -f
## CC all cleans out the deleted files from DB that was deleted above
drush cc all

date +%FT%H%M
#CC ALL some times display changes to do that not are visble before the CC ALL
#Run FR
drush fra -v --yes || exit 5
drush cc all || exit 6

date +%FT%H%M
#Run updateDB
drush updatedb --yes --verbose || exit 7
drush cc all || exit 8

date +%FT%H%M
#Sometimes more modules may be updated after updatedb & CC
drush fra -v --yes || exit 9
drush cc all || exit 10

#Backup DB
#drush sql-dump --structure-tables-key=common > /nettapp_w3/pg_dump/pre_staging/w3.uib.no-staging-backup.$(date -I)T$(date +%H%M%S).postupgrade.sql || exit 1
date +%FT%H%M

#Display that all is OK to user
drush fl

#drush vset maintenance_mode 0
drush cc all

